name: Hello World

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Print current date
        run: date
      
      - name: On Pull Request
        if: github.event_name == 'pull_request'
        run: echo "I am going to make change to README"

      - name: On Push
        if: github.event_name == 'push'
        run: echo "I want to add the date to README"

      - name: Print README.md
        run: cat README.md